# Create the namespace 'datacenter'
apiVersion: v1
kind: Namespace
metadata:
  name: datacenter
---

# Create the service 'httpd-service' as a nodeport service on port 30080
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: datacenter
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
---

# Create the deployment 'httpd-deploy' with 4 replicas using httpd:2.4.27 image.
# Deployment should use RollingUpdate strategy with 2 max unavailable and 1 max surge.
# Deployment should use the service 'httpd-service' as a selector.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: datacenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.28
        ports:
        - containerPort: 80
        # Enforce resource limits
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---

