# YAML to setup the K8s deployment as per task specification.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-deploy-nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-nautilus
  template:
    metadata:
      labels:
        app: ic-nautilus
    spec:
      containers:
      - name: ic-main-nautilus
        image: fedora:latest
        command: ["/bin/bash", "-c", 'while true; do cat /ic/beta; sleep 5; done']
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ic-volume-nautilus
          mountPath: /ic
      initContainers:
      - name: ic-msg-nautilus
        image: fedora:latest
        command: ['/bin/bash', '-c', 'echo Init Done - Welcome to xFusionCorp Industries > /ic/beta']
        volumeMounts:
        - name: ic-volume-nautilus
          mountPath: /ic
      volumes:
      - name: ic-volume-nautilus
        emptyDir: {}
        