# YAML Code for KodeKloud Engineer Task: Create Deployments in Kubernetes Cluster.
# Written by Sam Cole - https://github.com/sweatycoodu/
# As always - give it a go first - use if stuck.

# Deployment for httpd:latest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /httpd-data
        - name: httpd-config
          mountPath: /httpd
      volumes:
      - name: data
        emptyDir: {}
      - name: httpd-config